config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  get 'builder', to: 'static_pages#builder'
  get 'builder_location', to: 'static_pages#builder_location'
  get 'location', to: 'static_pages#location'
  get 'materials', to: 'static_pages#materials'
  
  
  root to: 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  has_ancestry
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end

    def builder
    end

    def builder_location
    end
    
    def location
    end

    def materials
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if current_user %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Register", new_user_registration_path %>
      <%= link_to "Login", new_user_session_path %>
    <% end %>

    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div id="background"></div 

          <%= render "shared/application_nav" %>
        </div>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/shared/_application_nav.html.erb
<div>
	<div><%= link_to "Home", root_path %></div>
	<div><%= link_to "Builder", builder_path %></div>
	<div><%= link_to "BuilderLocation", builder_location_path %></div>
	<div><%= link_to "Location", location_path %></div>
	<div><%= link_to "materials", materials_path %></div>
</div>

app/views/static_pages/builder.html.erb
<h1>Builders</h1>

app/views/static_pages/builder_location.html.erb
<h1>Builder Locations</h1>

app/views/static_pages/home.html.erb
<%= stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="app-card-container">
  <h1>Hello</h1>
</div>

app/views/static_pages/location.html.erb
<h1>Location</h1>

app/views/static_pages/materials.html.erb
<h1>Materials</h1>